spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:49161/xe
    username: local
    password: local
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    show-sql: true
#    hibernate:
#      ddl-auto: update
